// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// // ...



/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANmxCszY5oLpg7oGTyD6HjQajeC5x7OmQ',
    appId: '1:109312290924:web:0366bc469a14c80e95e849',
    messagingSenderId: '109312290924',
    projectId: 'excelet-academy',
    authDomain: 'excelet-academy.firebaseapp.com',
    storageBucket: 'excelet-academy.firebasestorage.app',
    measurementId: 'G-B98YZ8FR5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs-TOlz72YqRQlj484r8QVKBRSbXBJTX4',
    appId: '1:109312290924:android:893bf9d9655669c595e849',
    messagingSenderId: '109312290924',
    projectId: 'excelet-academy',
    storageBucket: 'excelet-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ9HWMTAhnWU17m6GFES_D-26rZxUL1ig',
    appId: '1:109312290924:ios:6cd23b326c88127495e849',
    messagingSenderId: '109312290924',
    projectId: 'excelet-academy',
    storageBucket: 'excelet-academy.firebasestorage.app',
    iosBundleId: 'com.exceletacademy.lms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ9HWMTAhnWU17m6GFES_D-26rZxUL1ig',
    appId: '1:109312290924:ios:b207df02173718c795e849',
    messagingSenderId: '109312290924',
    projectId: 'excelet-academy',
    storageBucket: 'excelet-academy.firebasestorage.app',
    iosBundleId: 'com.example.lmsSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANmxCszY5oLpg7oGTyD6HjQajeC5x7OmQ',
    appId: '1:109312290924:web:fb78453fdc74fcf695e849',
    messagingSenderId: '109312290924',
    projectId: 'excelet-academy',
    authDomain: 'excelet-academy.firebaseapp.com',
    storageBucket: 'excelet-academy.firebasestorage.app',
    measurementId: 'G-SLZRJDVFHD',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
